<?php

namespace Database\Seeders;

use App\Models\PricingPackage;
use Illuminate\Database\Seeder;

class PricingPackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Semua fitur dibuka untuk semua paket
        // Yang membedakan hanya limit/quota (jumlah WA, human agents, dll)
        $allFeatures = [
            'crm_chat',
            'human_agents',
            'broadcast_wa',
            'broadcast_group',
            'scraper_gmaps',
            'scraper_contacts',
            'scraper_groups',
            'reply_manual',
            'chatbot_ai',
            'platforms',
            'templates',
            'master_data',
        ];

        $packages = [
            [
                'name' => 'Trial',
                'slug' => 'trial',
                'description' => 'Paket trial 3 hari untuk mencoba semua fitur',
                'price' => 0.00,
                'currency' => 'IDR',
                'period' => 3,
                'period_unit' => 'day',
                'features' => [
                    'Akses Semua Fitur (3 Hari)',
                    'Human Agent (1)',
                    'AI Agent (1)',
                    'Nomor WhatsApp (1)',
                    'Akun Facebook Messenger (1)',
                    'Akun Instagram (1)',
                    'Akun Telegram (1)',
                    'Broadcast WhatsApp (Terbatas)',
                    'Broadcast Email (Terbatas)',
                    'Template WhatsApp (10)',
                    'Template Email (10)',
                    'Scraping Contacts (500/monthly)',
                    'Auto-Reply Manual (1)',
                    'Widget LiveChat (1)',
                ],
                'feature_keys' => $allFeatures,
                'is_featured' => false,
                'is_active' => true,
                'order' => 0,
                'button_text' => 'Coba Gratis',
                'button_url' => '/register',
            ],
            [
                'name' => 'Basic',
                'slug' => 'basic',
                'description' => 'Paket dasar untuk memulai otomasi customer service',
                'price' => 249000.00,
                'currency' => 'IDR',
                'period' => 30,
                'period_unit' => 'day',
                'features' => [
                    'Human Agent (1)',
                    'AI Agent (1)',
                    'Nomor WhatsApp (1)',
                    'Akun Facebook Messenger (1)',
                    'Akun Instagram (1)',
                    'Akun Telegram (1)',
                    'Broadcast WhatsApp (Unlimited)',
                    'Broadcast Email (Unlimited)',
                    'Template WhatsApp (25)',
                    'Template Email (25)',
                    'Scraping Contacts WhatsApp (1,000/monthly)',
                    'Scraping Contacts Google Maps (1,000/monthly)',
                    'Auto-Reply Manual (1)',
                    'Widget LiveChat (1)',
                    'Integrasi Cek Ongkir',
                    'Integrasi Google Sheet',
                ],
                'feature_keys' => $allFeatures,
                'is_featured' => false,
                'is_active' => true,
                'order' => 1,
                'button_text' => 'Pilih Paket',
                'button_url' => '/register',
            ],
            [
                'name' => 'Medium',
                'slug' => 'medium',
                'description' => 'Paket menengah untuk bisnis yang berkembang',
                'price' => 449000.00,
                'currency' => 'IDR',
                'period' => 30,
                'period_unit' => 'day',
                'features' => [
                    'Human Agent (3)',
                    'AI Agent (3)',
                    'Nomor WhatsApp (3)',
                    'Akun Facebook Messenger (3)',
                    'Akun Instagram (3)',
                    'Akun Telegram (3)',
                    'Broadcast WhatsApp (Unlimited)',
                    'Broadcast Email (Unlimited)',
                    'Template WhatsApp (75)',
                    'Template Email (75)',
                    'Scraping Contacts WhatsApp (3,000/monthly)',
                    'Scraping Contacts Google Maps (3,000/monthly)',
                    'Auto-Reply Manual (3)',
                    'Widget LiveChat (3)',
                    'Integrasi Cek Ongkir',
                    'Integrasi Google Sheet',
                ],
                'feature_keys' => $allFeatures,
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
                'button_text' => 'Pilih Paket',
                'button_url' => '/register',
            ],
            [
                'name' => 'Pro',
                'slug' => 'pro',
                'description' => 'Paket profesional dengan fitur lebih lengkap',
                'price' => 949000.00,
                'currency' => 'IDR',
                'period' => 30,
                'period_unit' => 'day',
                'features' => [
                    'Human Agent (7)',
                    'AI Agent (7)',
                    'Nomor WhatsApp (7)',
                    'Akun Facebook Messenger (7)',
                    'Akun Instagram (7)',
                    'Akun Telegram (7)',
                    'Broadcast WhatsApp (Unlimited)',
                    'Broadcast Email (Unlimited)',
                    'Template WhatsApp (100)',
                    'Template Email (100)',
                    'Scraping Contacts WhatsApp (7,000/monthly)',
                    'Scraping Contacts Google Maps (7,000/monthly)',
                    'Auto-Reply Manual (7)',
                    'Widget LiveChat (7)',
                    'Integrasi Cek Ongkir',
                    'Integrasi Google Sheet',
                ],
                'feature_keys' => $allFeatures,
                'is_featured' => false,
                'is_active' => true,
                'order' => 3,
                'button_text' => 'Pilih Paket',
                'button_url' => '/register',
            ],
            [
                'name' => 'Enterprise',
                'slug' => 'enterprise',
                'description' => 'Paket lengkap untuk perusahaan dengan fitur unlimited',
                'price' => 1449000.00,
                'currency' => 'IDR',
                'period' => 30,
                'period_unit' => 'day',
                'features' => [
                    'Human Agent (unlimited)',
                    'AI Agent (unlimited)',
                    'Nomor WhatsApp (unlimited)',
                    'Akun Facebook Messenger (unlimited)',
                    'Akun Instagram (unlimited)',
                    'Akun Telegram (unlimited)',
                    'Broadcast WhatsApp (Unlimited)',
                    'Broadcast Email (Unlimited)',
                    'Template WhatsApp (unlimited)',
                    'Template Email (unlimited)',
                    'Scraping Contacts WhatsApp (unlimited/monthly)',
                    'Scraping Contacts Google Maps (unlimited/monthly)',
                    'Auto-Reply Manual (unlimited)',
                    'Widget LiveChat (unlimited)',
                    'Integrasi Cek Ongkir',
                    'Integrasi Google Sheet',
                ],
                'feature_keys' => $allFeatures,
                'is_featured' => false,
                'is_active' => true,
                'order' => 4,
                'button_text' => 'Hubungi Kami',
                'button_url' => '/contact',
            ],
        ];

        foreach ($packages as $package) {
            PricingPackage::updateOrCreate(
                ['slug' => $package['slug']],
                $package
            );
        }
    }
}
