import {
    ArrowRight,
    BarChart3,
    Bell,
    Bot,
    Calculator,
    CheckCircle,
    Grid,
    Languages,
    Megaphone,
    MessageCircle,
    MessageSquare,
    MonitorPlay,
    Sparkles,
    TrendingUp,
    Users,
    Zap,
} from 'lucide-react';

export const iconMap: Record<string, any> = {
    ArrowRight,
    BarChart3,
    Bell,
    Bot,
    Calculator,
    CheckCircle,
    Grid,
    Languages,
    Megaphone,
    MessageCircle,
    MessageSquare,
    MonitorPlay,
    Sparkles,
    TrendingUp,
    Users,
    Zap,
};
