<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Google Map Places Export</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            color: #333;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #2563eb;
        }
        .header h1 {
            color: #2563eb;
            font-size: 18px;
            margin-bottom: 5px;
        }
        .header p {
            color: #64748b;
            font-size: 9px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        thead {
            background-color: #2563eb;
            color: white;
        }
        th {
            padding: 8px 6px;
            text-align: left;
            font-weight: 600;
            font-size: 9px;
            border: 1px solid #1e40af;
        }
        td {
            padding: 6px;
            border: 1px solid #e2e8f0;
            font-size: 8px;
        }
        tbody tr:nth-child(even) {
            background-color: #f8fafc;
        }
        tbody tr:hover {
            background-color: #f1f5f9;
        }
        .footer {
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            font-size: 8px;
            color: #94a3b8;
        }
        .rating {
            color: #f59e0b;
            font-weight: 600;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Google Map Places Export</h1>
        <p>Export Date: {{ $exportDate }}</p>
        <p>Total Records: {{ count($places) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 15%;">Name</th>
                <th style="width: 10%;">Kecamatan</th>
                <th style="width: 10%;">Location</th>
                <th style="width: 10%;">Category</th>
                <th style="width: 5%;">Rating</th>
                <th style="width: 5%;">Reviews</th>
                <th style="width: 20%;">Address</th>
                <th style="width: 10%;">Phone</th>
                <th style="width: 15%;">Website</th>
            </tr>
        </thead>
        <tbody>
            @foreach($places as $place)
            <tr>
                <td>{{ $place->name }}</td>
                <td>{{ $place->kecamatan }}</td>
                <td>{{ $place->location }}</td>
                <td>{{ $place->category }}</td>
                <td class="rating">{{ $place->rating ?? '-' }}</td>
                <td>{{ $place->review_count ?? '-' }}</td>
                <td>{{ $place->address ?? '-' }}</td>
                <td>{{ $place->phone ?? '-' }}</td>
                <td style="font-size: 7px;">{{ $place->website ? Str::limit($place->website, 30) : '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by ChatCepat Google Maps Scraper</p>
    </div>
</body>
</html>
